### ISSUE TITLE
Rewie 10.09.2020

### ISSUE THREAD

**Issue by doroshenkoam** [JimTheBeam/Twenty-One#1]
1. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L11 названия таблиц с маленькой буквы;
2. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L7 в отдельный пакет;
3. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L18 функции не должны принтовать, а должны возвращать значения;
4. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L23 тут напрашивается файл конфигурации;
5. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L23 тут массив не надо, делай для каждого файла;
6. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L35 также как в пункте 4,5;
7. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L46 также как в пункте 4,5;
8. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L52 костыль, тут нужен split;
9. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L55 инструкция switch/case;
10. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L85 закоментить или выпилить;
11. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L92 тут надо просто сделать select и отдать все в функцию кэша, не обязательно так сложно;
12. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L117 есть в main. Вообще такую штуку надо делать с помощью defer;
13. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L140 все ли ошибки бд покрывает?
14. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L159 тут либо ты все в кэш пишешь, либо бегаешь в базу;
15. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L173 также как в 14;
16. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L187 также как в 14,15;
17. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L170 почитай про работу с ошибками в питоне.
18. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L236 defer и рядом с открытием;
19. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L206 напрашивается файл конфигурации;
20. https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L216 не обязательно делать аллокации, можно сразу функции передавать в https://github.com/JimTheBeam/Twenty-One/blob/telegram_bot/database/card_db.py#L221

**Comment by JimTheBeam** [comment]
закрыты
